import type { AboutSection, ContentItem, LocalizedText, MediaAsset, RegionContent, SiteData } from "./index";

// Public copy is deliberately required in every locale; there is no English fallback.
const t = (en: string, ar: string, fr: string, nl: string): LocalizedText => ({ en, ar, fr, nl });
const same = (value: string): LocalizedText => t(value, value, value, value);
const media = (id: string, file: string, alt: LocalizedText, focalX = 50, focalY = 50): MediaAsset => ({
  id, url: file.startsWith("/") ? file : `/starter-media/${file}`, alt, focalX, focalY, zoom: 1,
});
const section = (id: string, title: LocalizedText, body: LocalizedText, bullets?: LocalizedText[], image?: MediaAsset): AboutSection => ({ id, title, body, bullets, media: image });

function item(id: string, type: ContentItem["type"], title: LocalizedText, summary: LocalizedText, body: LocalizedText, cover?: MediaAsset, extras: Partial<ContentItem> = {}): ContentItem {
  return { id, type, slug: same(id), title, summary, body, cover, status: "published", ...extras };
}

function page(id: string, title: LocalizedText, summary: LocalizedText, body: LocalizedText, cover?: MediaAsset, extras: Partial<ContentItem> = {}): ContentItem {
  return item(id, "pages", title, summary, body, cover, {
    seo: {
      title,
      description: summary,
      keywords: t(
        "MOVERA, Belgium, mobility, autonomous vehicles, connected transport",
        "موفيرا، بلجيكا، التنقل، المركبات ذاتية القيادة، النقل المتصل",
        "MOVERA, Belgique, mobilité, véhicules autonomes, transport connecté",
        "MOVERA, België, mobiliteit, autonome voertuigen, verbonden vervoer",
      ),
    },
    ...extras,
  });
}

const hero = media("movera-hero", "movera-autonomy-hero.webp", t(
  "Autonomous electric shuttle moving through a Belgian city",
  "مركبة كهربائية ذاتية القيادة تسير في مدينة بلجيكية",
  "Navette électrique autonome circulant dans une ville belge",
  "Autonome elektrische shuttle in een Belgische stad",
));

const img = {
  serviceAutonomy: media("service-autonomy", "movera-service-autonomy.webp", t("Engineers calibrating an autonomous shuttle on a Belgian test street", "مهندسون يعايرون مركبة ذاتية القيادة في شارع اختبار بلجيكي", "Des ingénieurs calibrent une navette autonome sur une rue d’essai belge", "Ingenieurs kalibreren een autonome shuttle in een Belgische teststraat")),
  serviceFleet: media("service-fleet", "movera-service-fleet.webp", t("Electric service fleet at a connected charging depot", "أسطول خدمات كهربائي في مستودع شحن متصل", "Flotte de service électrique dans un dépôt de recharge connecté", "Elektrische servicevloot in een verbonden laadsite")),
  serviceOperations: media("service-operations", "movera-service-operations.webp", t("Shuttle, tram, cyclists and pedestrians sharing a Belgian street", "مركبة وترام ودراجون ومشاة يتشاركون شارعاً بلجيكياً", "Navette, tram, cyclistes et piétons partagent une rue belge", "Shuttle, tram, fietsers en voetgangers delen een Belgische straat")),
  serviceExperience: media("service-experience", "movera-service-experience.webp", t("Calm passenger experience inside an autonomous shuttle", "تجربة هادئة للركاب داخل مركبة ذاتية القيادة", "Expérience passager sereine à bord d’une navette autonome", "Rustige passagierservaring in een autonome shuttle")),
  productCommand: media("product-command", "movera-product-command.webp", t("Mobility operations team in a bright control room", "فريق عمليات التنقل داخل غرفة تحكم مضيئة", "Équipe mobilité dans une salle de contrôle lumineuse", "Mobiliteitsteam in een lichte controlekamer")),
  productPerception: media("product-perception", "movera-product-perception.webp", t("Vehicle perception sensor being calibrated in a laboratory", "معايرة مستشعر إدراك المركبة داخل مختبر", "Calibration d’un capteur de perception en laboratoire", "Kalibratie van een voertuigperceptiesensor in een labo")),
  productMotion: media("product-motion", "movera-product-motion-os.webp", t("Belgian boulevard coordinating public transport, vehicles and cyclists", "شارع بلجيكي يجمع النقل العام والمركبات والدراجات", "Boulevard belge où cohabitent transports publics, véhicules et cyclistes", "Belgische boulevard waar openbaar vervoer, voertuigen en fietsers samenkomen")),
  productTwin: media("product-twin", "movera-product-twin.webp", t("Mobility team working around a physical city model", "فريق تنقل يعمل حول نموذج مادي لمدينة", "Équipe mobilité autour d’une maquette urbaine", "Mobiliteitsteam rond een fysieke stadsmaquette")),
  projectBrussels: media("project-brussels", "movera-project-brussels.webp", t("Autonomous shuttle sharing a rainy Brussels street with a tram and cyclists", "مركبة ذاتية تتشارك شارعاً ممطراً في بروكسل مع الترام والدراجات", "Navette autonome dans une rue bruxelloise pluvieuse avec tram et cyclistes", "Autonome shuttle in een regenachtige Brusselse straat met tram en fietsers")),
  projectAntwerp: media("project-antwerp", "movera-project-antwerp.webp", t("Electric service vehicles in the Port of Antwerp corridor", "مركبات خدمات كهربائية في ممر ميناء أنتويرب", "Véhicules de service électriques dans le corridor du port d’Anvers", "Elektrische servicevoertuigen in de Antwerpse havencorridor")),
  projectCockpit: media("project-cockpit", "movera-project-cockpit.webp", t("Passenger and operator inside a connected vehicle cockpit", "راكبة ومشغّل داخل قمرة مركبة متصلة", "Passagère et opérateur dans un cockpit connecté", "Passagier en operator in een verbonden cockpit")),
  projectCorridor: media("project-corridor", "movera-project-corridor.webp", t("Accessible connected corridor with shuttle, bus and cyclists", "ممر متصل ومتاح يضم مركبة وحافلة ودراجات", "Corridor connecté et accessible avec navette, bus et cyclistes", "Toegankelijke verbonden corridor met shuttle, bus en fietsers")),
  newsIntro: media("news-intro", "movera-news-introduction.webp", t("Autonomous shuttle in Brussels at first light", "مركبة ذاتية في بروكسل مع ضوء الصباح", "Navette autonome à Bruxelles au lever du jour", "Autonome shuttle in Brussel bij het eerste licht")),
  newsEdge: media("news-edge", "movera-news-edge.webp", t("Engineer installing edge hardware in a shuttle", "مهندس يثبت حوسبة طرفية داخل مركبة", "Ingénieur installant un calculateur embarqué dans une navette", "Ingenieur installeert edgehardware in een shuttle")),
  newsBelgium: media("news-belgium", "movera-news-belgium.webp", t("Belgian mobility stakeholders meeting beside a shuttle and tram", "أطراف منظومة التنقل البلجيكية تجتمع بجوار مركبة وترام", "Acteurs belges de la mobilité réunis près d’une navette et d’un tram", "Belgische mobiliteitspartners bijeen naast een shuttle en tram")),
  blogOperator: media("blog-operator", "movera-blog-operator.webp", t("Two operators reviewing a mobility exception", "مشغّلان يراجعان استثناءً في نظام التنقل", "Deux opérateurs examinent une exception de mobilité", "Twee operatoren beoordelen een mobiliteitsuitzondering")),
  blogTrust: media("blog-trust", "movera-blog-trust.webp", t("Passenger and mobility host inside an accessible shuttle", "راكبة ومضيف تنقل داخل مركبة مهيأة", "Passagère et hôte mobilité dans une navette accessible", "Passagier en mobiliteitshost in een toegankelijke shuttle")),
  blogSignals: media("blog-signals", "movera-blog-signals.webp", t("Engineers reviewing sensor evidence in a mobility laboratory", "مهندسون يراجعون أدلة المستشعرات في مختبر تنقل", "Ingénieurs examinant des preuves capteurs dans un laboratoire mobilité", "Ingenieurs beoordelen sensorbewijs in een mobiliteitslabo")),
  innovationConfidence: media("innovation-confidence", "movera-innovation-confidence.webp", t("Engineers testing perception confidence in a vehicle laboratory", "مهندسون يختبرون ثقة الإدراك في مختبر مركبات", "Ingénieurs testant la confiance de perception en laboratoire", "Ingenieurs testen perceptievertrouwen in een voertuiglabo")),
  innovationSimulation: media("innovation-simulation", "movera-innovation-simulation.webp", t("Team rehearsing mobility scenarios on a city model", "فريق يختبر سيناريوهات تنقل على نموذج مدينة", "Équipe répétant des scénarios sur une maquette urbaine", "Team beproeft scenario’s op een stadsmaquette")),
  innovationCurb: media("innovation-curb", "movera-innovation-curb.webp", t("Researchers observing an accessible Belgian kerbside", "باحثون يراقبون رصيفاً بلجيكياً مهيأً", "Chercheurs observant un bord de voirie belge accessible", "Onderzoekers observeren een toegankelijke Belgische stoeprand")),
  careersTeam: media("careers-team", "movera-careers-team.webp", t("MOVERA team collaborating in a mobility studio", "فريق موفيرا يتعاون داخل استوديو للتنقل", "Équipe MOVERA collaborant dans un studio mobilité", "MOVERA-team werkt samen in een mobiliteitsstudio")),
  careersData: media("careers-data", "movera-careers-data.webp", t("Data and test engineers beside an autonomous shuttle", "مهندسا بيانات واختبار بجوار مركبة ذاتية", "Ingénieurs data et essais près d’une navette autonome", "Data- en testingenieurs naast een autonome shuttle")),
  careersIntegration: media("careers-integration", "movera-careers-integration.webp", t("Systems team coordinating an autonomous vehicle test", "فريق أنظمة ينسق اختبار مركبة ذاتية", "Équipe systèmes coordonnant un essai de véhicule autonome", "Systeemteam coördineert een autonome voertuigtest")),
  aboutStudio: media("about-studio", "movera-about-studio.webp", t("Mobility team working around a shuttle and city model", "فريق تنقل يعمل حول مركبة ونموذج مدينة", "Équipe mobilité autour d’une navette et d’une maquette urbaine", "Mobiliteitsteam rond een shuttle en stadsmaquette")),
  aboutHistory: media("about-history", "movera-about-history.webp", t("Vehicle sensors and engineering artefacts on a workbench", "مستشعرات مركبات ونماذج هندسية على طاولة عمل", "Capteurs et objets d’ingénierie sur un établi", "Voertuigsensoren en engineeringobjecten op een werkbank")),
  aboutLeadership: media("about-leadership", "movera-about-leadership.webp", t("Mobility leadership team making a decision around a city model", "فريق قيادة التنقل يتخذ قراراً حول نموذج مدينة", "Équipe de direction mobilité décidant autour d’une maquette urbaine", "Mobiliteitsleiding neemt een beslissing rond een stadsmaquette")),
  aboutVision: media("about-vision", "movera-about-vision.webp", t("A connected Belgian street viewed from a mobility planning studio", "شارع بلجيكي متصل يُرى من استوديو لتخطيط التنقل", "Rue belge connectée vue depuis un studio de planification mobilité", "Verbonden Belgische straat gezien vanuit een mobiliteitsstudio")),
  aboutAssurance: media("about-assurance", "movera-about-assurance.webp", t("Engineering, operations and safety specialists reviewing vehicle evidence", "مختصون في الهندسة والعمليات والسلامة يراجعون أدلة المركبة", "Spécialistes en ingénierie, opérations et sécurité examinant les preuves véhicule", "Specialisten in engineering, operaties en veiligheid beoordelen voertuigbewijs")),
  aboutLeadershipNote: media("about-leadership-note", "movera-about-leadership-note.webp", t("Mobility leader looking across an autonomous shuttle test street", "قائد في مجال التنقل ينظر إلى شارع اختبار لمركبة ذاتية", "Responsable mobilité observant une rue d’essai pour navette autonome", "Mobiliteitsleider kijkt uit over een teststraat voor een autonome shuttle")),
  regionBrussels: media("region-brussels", "movera-region-brussels.webp", t("Connected mobility on a Brussels boulevard", "تنقل متصل في شارع ببروكسل", "Mobilité connectée sur un boulevard bruxellois", "Verbonden mobiliteit op een Brusselse boulevard")),
  regionFlanders: media("region-flanders", "movera-region-flanders.webp", t("Electric fleet on a green Flemish innovation corridor", "أسطول كهربائي في ممر ابتكار أخضر في فلاندرز", "Flotte électrique dans un corridor d’innovation flamand", "Elektrische vloot in een groene Vlaamse innovatiecorridor")),
  regionWallonia: media("region-wallonia", "movera-region-wallonia.webp", t("Autonomous shuttle connecting a Walloon town and rail stop", "مركبة ذاتية تربط بلدة والونية بمحطة قطار", "Navette autonome reliant une ville wallonne à une gare", "Autonome shuttle verbindt een Waalse stad met het station")),
};

const services: ContentItem[] = [
  item("autonomy-systems", "services", t("Autonomy Systems", "أنظمة القيادة الذاتية", "Systèmes autonomes", "Autonomiesystemen"), t("Build perception, planning and control that teams can test, explain and trust.", "نبني الإدراك والتخطيط والتحكم بطريقة قابلة للاختبار والتفسير والثقة.", "Concevoir une perception, une planification et un contrôle testables et explicables.", "Bouw perceptie, planning en aansturing die teams kunnen testen en uitleggen."), t("MOVERA connects sensor evidence, vehicle behaviour and human review in one engineering workflow.\nFrom operating domain to road-test evidence, clear gates guide safety, exceptions and release decisions.", "تربط موفيرا أدلة المستشعرات بسلوك المركبة والمراجعة البشرية ضمن مسار هندسي واحد.\nننتقل من نطاق التشغيل إلى أدلة الاختبار الميداني عبر بوابات واضحة للسلامة والاستثناءات وقرارات الإطلاق.", "MOVERA relie preuves capteurs, comportement du véhicule et revue humaine dans un même parcours d’ingénierie.\nDu domaine opérationnel aux essais routiers, des jalons clairs guident sécurité, exceptions et mise en service.", "MOVERA brengt sensorgegevens, voertuiggedrag en menselijke beoordeling samen in één engineeringflow.\nVan operationeel domein tot wegtestbewijs sturen duidelijke poorten veiligheid, uitzonderingen en vrijgave."), img.serviceAutonomy, { category: "Autonomy", sector: "Autonomous Vehicles", featured: true, displayOrder: 0, tags: ["perception", "planning", "validation"], relatedIds: ["perception-layer", "brussels-perception-pilot"] }),
  item("fleet-intelligence", "services", t("Fleet Intelligence", "ذكاء الأساطيل", "Intelligence de flotte", "Vlootintelligentie"), t("Turn live fleet signals into decisions before service is affected.", "نحوّل إشارات الأسطول الحية إلى قرارات قبل تأثر الخدمة.", "Transformer les signaux de flotte en décisions avant que le service ne soit touché.", "Zet live vlootsignalen om in beslissingen vóór de dienstverlening geraakt wordt."), t("MOVERA unifies vehicle health, charging, missions and route context without burying operators in dashboards.\nDispatch, maintenance and customer operations work from the same evidence and next action.", "توحّد موفيرا حالة المركبات والشحن والمهام وسياق المسارات من دون إغراق المشغّلين بلوحات المتابعة.\nتعمل فرق التوجيه والصيانة وخدمة العملاء انطلاقاً من الدليل نفسه والخطوة التالية نفسها.", "MOVERA réunit état des véhicules, recharge, missions et itinéraires sans noyer les opérateurs sous les tableaux de bord.\nDispatching, maintenance et opérations clients partagent la même preuve et la même prochaine action.", "MOVERA verenigt voertuigconditie, laden, opdrachten en routecontext zonder operatoren te verdrinken in dashboards.\nDispatching, onderhoud en klantoperaties werken met hetzelfde bewijs en dezelfde volgende actie."), img.serviceFleet, { category: "Operations", sector: "Fleet Operations", featured: true, displayOrder: 1, tags: ["fleet", "maintenance", "dispatch"], relatedIds: ["movera-command", "antwerp-fleet-flow"] }),
  item("mobility-operations", "services", t("Mobility Operations", "عمليات التنقل", "Opérations de mobilité", "Mobiliteitsoperaties"), t("Coordinate vehicles, people and infrastructure as one service in motion.", "ننسّق المركبات والأشخاص والبنية التحتية كخدمة واحدة تتحرك بانسجام.", "Coordonner véhicules, équipes et infrastructure comme un seul service en mouvement.", "Coördineer voertuigen, mensen en infrastructuur als één bewegende dienst."), t("Reliable mobility depends on handovers between vehicle and operator, depot and street, plan and exception.\nMOVERA makes those moments visible and gives each next action a clear owner.", "تعتمد موثوقية التنقل على انتقال المسؤولية بين المركبة والمشغّل، والمستودع والشارع، والخطة والاستثناء.\nتجعل موفيرا هذه اللحظات واضحة وتمنح كل إجراء تالٍ مسؤولاً معروفاً.", "La fiabilité se joue dans les relais entre véhicule et opérateur, dépôt et rue, plan et exception.\nMOVERA rend ces moments visibles et attribue clairement chaque action suivante.", "Betrouwbare mobiliteit draait om overdrachten tussen voertuig en operator, depot en straat, planning en uitzondering.\nMOVERA maakt die momenten zichtbaar en geeft elke volgende actie een duidelijke eigenaar."), img.serviceOperations, { category: "Operations", sector: "Connected Infrastructure", featured: true, displayOrder: 2, tags: ["orchestration", "exceptions", "service"], relatedIds: ["motion-os", "adaptive-mobility-corridor"] }),
  item("vehicle-experience", "services", t("Vehicle Experience", "تجربة المركبة", "Expérience à bord", "Voertuigervaring"), t("Design autonomous journeys that explain themselves at the right moment.", "نصمم رحلات ذاتية تشرح ما يحدث للراكب في اللحظة المناسبة.", "Concevoir des trajets autonomes qui s’expliquent au bon moment.", "Ontwerp autonome ritten die op het juiste moment duidelijkheid geven."), t("Trust is built through boarding, route changes, handover and arrival. MOVERA designs information and controls around those moments.\nAccessibility and human factors are system requirements from the start, not a final interface pass.", "تُبنى الثقة عند الصعود وتغيير المسار وانتقال التحكم والوصول. تصمم موفيرا المعلومات وعناصر التحكم حول هذه اللحظات.\nسهولة الوصول والعوامل البشرية متطلبات للنظام منذ البداية، وليست تحسيناً أخيراً للواجهة.", "La confiance naît à l’embarquement, lors d’un changement de route, d’une reprise en main et à l’arrivée. MOVERA conçoit l’information autour de ces moments.\nAccessibilité et facteurs humains sont des exigences du système dès le départ.", "Vertrouwen ontstaat bij instappen, routewijziging, overname en aankomst. MOVERA ontwerpt informatie en bediening rond die momenten.\nToegankelijkheid en human factors zijn van bij de start systeemvereisten."), img.serviceExperience, { category: "Experience", sector: "Vehicle Experience", featured: true, displayOrder: 3, tags: ["human factors", "accessibility", "cockpit"], relatedIds: ["connected-cockpit", "trust-before-boarding"] }),
];

const products: ContentItem[] = [
  item("movera-command", "products", same("MOVERA Command"), t("One operational view for the next mobility decision.", "صورة تشغيلية واحدة تقود قرار التنقل التالي.", "Une vue opérationnelle unique pour décider du prochain mouvement.", "Eén operationeel beeld voor de volgende mobiliteitsbeslissing."), t("Command brings missions, vehicle state, confidence and approvals into a focused workspace. Operators see what changed, why it matters and who owns the next action.\nDispatch, fleet health and incidents share one accountable decision trail.", "تجمع المنصة المهام وحالة المركبات ومؤشرات الثقة والموافقات في مساحة مركزة. يرى المشغّل ما تغيّر ولماذا يهم ومن يملك الإجراء التالي.\nتشترك عمليات التوجيه وصحة الأسطول والحوادث في سجل قرار واحد خاضع للمساءلة.", "Command réunit missions, état des véhicules, confiance et validations dans un espace ciblé. L’opérateur comprend ce qui change, pourquoi et qui agit ensuite.\nDispatching, santé de flotte et incidents partagent une même trace de décision.", "Command brengt opdrachten, voertuigstatus, vertrouwen en goedkeuringen samen. Operatoren zien wat wijzigde, waarom het telt en wie handelt.\nDispatching, vlootconditie en incidenten delen één controleerbaar beslisspoor."), img.productCommand, { category: "Operations platform", sector: "Fleet Operations", featured: true, displayOrder: 0, tags: ["missions", "approvals", "exceptions"], relatedIds: ["fleet-intelligence", "antwerp-fleet-flow"] }),
  item("perception-layer", "products", same("Perception Layer"), t("Make vehicle perception visible, explainable and ready to improve.", "نجعل إدراك المركبة مرئياً وقابلاً للتفسير والتحسين.", "Rendre la perception du véhicule visible, explicable et améliorable.", "Maak voertuigperceptie zichtbaar, uitlegbaar en verbeterbaar."), t("Perception Layer connects sensor context, detections, confidence and review events. Engineers can move from an exception to the exact evidence behind it.\nCompare, annotate and approve verified insight before it returns to development.", "تربط الطبقة سياق المستشعرات والاكتشافات ومستوى الثقة وأحداث المراجعة. ينتقل المهندس من الاستثناء إلى الدليل الدقيق خلفه.\nتُقارن المعرفة الموثقة وتُشرح وتُعتمد قبل إعادتها إلى التطوير.", "Perception Layer relie contexte capteur, détections, confiance et événements de revue. L’ingénieur passe d’une exception à la preuve exacte.\nLes enseignements vérifiés sont comparés, annotés et validés avant de revenir au développement.", "Perception Layer koppelt sensorcontext, detecties, vertrouwen en reviewmomenten. Ingenieurs gaan van een uitzondering naar het exacte bewijs.\nGevalideerde inzichten worden vergeleken, geannoteerd en goedgekeurd vóór ze terugkeren naar ontwikkeling."), img.productPerception, { category: "Vehicle intelligence", sector: "Autonomous Vehicles", featured: true, displayOrder: 1, tags: ["sensors", "confidence", "review"], relatedIds: ["autonomy-systems", "brussels-perception-pilot"] }),
  item("motion-os", "products", same("Motion OS"), t("Coordinate movement across vehicles, routes and service teams.", "ننسّق الحركة بين المركبات والمسارات وفرق الخدمة.", "Coordonner les mouvements entre véhicules, itinéraires et équipes.", "Coördineer beweging tussen voertuigen, routes en serviceteams."), t("Motion OS turns plans into missions with rules for priority, capacity, handover and recovery. Local vehicle decisions stay aligned with network intent.\nNew routes and vehicle types can join without rebuilding the operating backbone.", "يحوّل النظام الخطط إلى مهام بقواعد للأولوية والسعة وانتقال المسؤولية واستعادة الخدمة. وتبقى قرارات المركبات متسقة مع هدف الشبكة.\nيمكن إضافة مسارات ومركبات جديدة من دون إعادة بناء الأساس التشغيلي.", "Motion OS transforme les plans en missions avec des règles de priorité, capacité, relais et reprise. Les décisions locales restent alignées sur le réseau.\nDe nouveaux itinéraires et véhicules rejoignent le service sans reconstruire son socle.", "Motion OS zet plannen om in opdrachten met regels voor prioriteit, capaciteit, overdracht en herstel. Lokale beslissingen blijven afgestemd op het netwerk.\nNieuwe routes en voertuigtypes sluiten aan zonder de operationele ruggengraat opnieuw te bouwen."), img.productMotion, { category: "Orchestration layer", sector: "Connected Infrastructure", featured: true, displayOrder: 2, tags: ["routing", "handover", "orchestration"], relatedIds: ["mobility-operations", "adaptive-mobility-corridor"] }),
  item("mobility-twin", "products", same("Mobility Twin"), t("Rehearse mobility decisions before they reach a live street.", "نختبر قرارات التنقل قبل أن تصل إلى الشارع الفعلي.", "Répéter les décisions de mobilité avant leur arrivée dans la rue.", "Beproef mobiliteitsbeslissingen vóór ze de echte straat bereiken."), t("Mobility Twin combines service rules, fleet state and street context in a shared simulation. Teams test demand, incidents and infrastructure changes before committing resources.\nScenarios are compared through service outcomes and decision quality, not spectacle.", "يجمع التوأم الرقمي قواعد الخدمة وحالة الأسطول وسياق الشارع في محاكاة مشتركة. تختبر الفرق الطلب والحوادث وتغييرات البنية التحتية قبل تخصيص الموارد.\nتُقارن السيناريوهات وفق نتائج الخدمة وجودة القرار، لا وفق الاستعراض.", "Mobility Twin rassemble règles de service, état de flotte et contexte urbain dans une simulation partagée. Les équipes testent demande, incidents et changements avant d’engager les moyens.\nLes scénarios sont comparés par leurs résultats et la qualité des décisions.", "Mobility Twin combineert serviceregels, vlootstatus en straatcontext in één simulatie. Teams testen vraag, incidenten en wijzigingen vóór middelen worden ingezet.\nScenario’s worden vergeleken op service-uitkomst en besliskwaliteit."), img.productTwin, { category: "Simulation", sector: "Mobility Planning", featured: true, displayOrder: 3, tags: ["simulation", "scenarios", "planning"], relatedIds: ["mobility-simulation-studio", "adaptive-mobility-corridor"] }),
];

const projects: ContentItem[] = [
  item("brussels-perception-pilot", "projects", t("Brussels Urban Perception", "إدراك حضري في بروكسل", "Perception urbaine à Bruxelles", "Stedelijke perceptie in Brussel"), t("A reference programme for reading dense Belgian streets with accountable confidence.", "برنامج مرجعي لفهم شوارع بلجيكية كثيفة بدرجات ثقة قابلة للمراجعة.", "Un programme de référence pour lire les rues belges denses avec une confiance vérifiable.", "Een referentieprogramma om drukke Belgische straten te lezen met controleerbaar vertrouwen."), t("The programme studies how a shuttle interprets trams, cyclists, pedestrians, road works and changing weather in one shared street.\nDetections are paired with confidence and operator review so difficult moments become usable engineering evidence.", "يدرس البرنامج كيف تفهم المركبة الترام والدراجات والمشاة والأعمال المؤقتة وتغيّر الطقس في شارع واحد.\nترتبط الاكتشافات بدرجات الثقة ومراجعة المشغّل كي تصبح المواقف الصعبة أدلة هندسية قابلة للاستخدام.", "Le programme étudie la lecture simultanée des trams, cyclistes, piétons, chantiers et changements météo.\nLes détections sont associées à leur confiance et à la revue opérateur afin que les situations difficiles deviennent des preuves utiles.", "Het programma onderzoekt hoe een shuttle trams, fietsers, voetgangers, wegenwerken en wisselend weer interpreteert.\nDetecties worden gekoppeld aan vertrouwen en operatorreview, zodat moeilijke momenten bruikbaar engineeringbewijs worden."), img.projectBrussels, { category: "Reference programme", sector: "Autonomous Vehicles", client: "Urban mobility ecosystem", date: "2026", featured: true, displayOrder: 0, tags: ["Brussels", "perception", "mixed traffic"], relatedIds: ["perception-layer", "autonomy-systems"] }),
  item("antwerp-fleet-flow", "projects", t("Antwerp Fleet Flow", "تدفق الأسطول في أنتويرب", "Flux de flotte à Anvers", "Vlootdoorstroming in Antwerpen"), t("A coordinated service model for electric vehicles in a high-intensity port corridor.", "نموذج خدمة منسق لمركبات كهربائية في ممر مينائي عالي الكثافة.", "Un modèle coordonné pour des véhicules électriques dans un corridor portuaire intensif.", "Een gecoördineerd servicemodel voor elektrische voertuigen in een intensieve havencorridor."), t("Charging windows, vehicle readiness, mission priority and route conditions meet in one dispatch view.\nThe programme helps operators act early, protect service commitments and learn from every exception.", "تجتمع نوافذ الشحن وجاهزية المركبات وأولوية المهام وظروف المسار في صورة توجيه واحدة.\nيساعد البرنامج المشغّلين على التحرك المبكر وحماية الالتزامات والتعلم من كل استثناء.", "Fenêtres de recharge, disponibilité des véhicules, priorité des missions et état des itinéraires se retrouvent dans une même vue.\nLe programme aide les opérateurs à agir tôt, protéger le service et apprendre de chaque exception.", "Laadvensters, voertuiggereedheid, opdrachtprioriteit en routecondities komen samen in één dispatchbeeld.\nHet programma helpt operatoren vroeg handelen, serviceafspraken bewaken en leren van elke uitzondering."), img.projectAntwerp, { category: "Reference programme", sector: "Fleet Operations", client: "Port mobility operators", date: "2026", featured: true, displayOrder: 1, tags: ["Antwerp", "electric fleet", "dispatch"], relatedIds: ["movera-command", "fleet-intelligence"] }),
  item("connected-cockpit", "projects", t("Connected Cockpit", "قمرة القيادة المتصلة", "Cockpit connecté", "Verbonden cockpit"), t("A calmer interface for handover, route change and passenger confidence.", "واجهة أكثر هدوءاً لانتقال التحكم وتغيير المسار وثقة الركاب.", "Une interface plus sereine pour la reprise en main, le changement de route et la confiance.", "Een rustigere interface voor overname, routewijziging en vertrouwen."), t("This design study organises autonomy state, route intent and human control around three questions: what is happening, why and what can I do?\nPersistent visual noise is reduced; strong signals are reserved for moments that need attention.", "تنظم الدراسة حالة القيادة الذاتية وهدف المسار والتحكم البشري حول ثلاثة أسئلة: ماذا يحدث، ولماذا، وماذا أستطيع أن أفعل؟\nتقل الضوضاء البصرية الدائمة وتُحجز الإشارات القوية للحظات التي تستحق الانتباه.", "Cette étude organise l’état d’autonomie, l’intention de route et la reprise humaine autour de trois questions : que se passe-t-il, pourquoi et que puis-je faire ?\nLe bruit visuel permanent diminue; les signaux forts sont réservés aux moments importants.", "Deze studie ordent autonomiestatus, route-intentie en menselijke controle rond drie vragen: wat gebeurt er, waarom en wat kan ik doen?\nPermanente visuele ruis vermindert; sterke signalen blijven voor momenten die aandacht vragen."), img.projectCockpit, { category: "Design study", sector: "Vehicle Experience", client: "Vehicle platform teams", date: "2026", featured: true, displayOrder: 2, tags: ["cockpit", "handover", "accessibility"], relatedIds: ["vehicle-experience", "trust-before-boarding"] }),
  item("adaptive-mobility-corridor", "projects", t("Adaptive Mobility Corridor", "ممر تنقل متكيّف", "Corridor de mobilité adaptatif", "Adaptieve mobiliteitscorridor"), t("A corridor blueprint for public transport, shuttles, cyclists and accessible stops.", "تصور لممر ينسق النقل العام والمركبات والدراجات والمحطات المهيأة.", "Un schéma de corridor coordonnant transport public, navettes, cyclistes et arrêts accessibles.", "Een corridorconcept voor openbaar vervoer, shuttles, fietsers en toegankelijke haltes."), t("Vehicles and roadside infrastructure operate as one service system. Capacity, accessibility and local conditions guide how missions adapt.\nA shared simulation lets public and private operators examine trade-offs before changing street operations.", "تعمل المركبات والبنية التحتية على الطريق كنظام خدمة واحد. وتوجّه السعة وسهولة الوصول والظروف المحلية كيفية تكيف المهام.\nتتيح المحاكاة المشتركة للمشغّلين فهم المفاضلات قبل تغيير التشغيل في الشارع.", "Véhicules et infrastructure routière fonctionnent comme un même système. Capacité, accessibilité et contexte local font évoluer les missions.\nUne simulation partagée permet d’examiner les arbitrages avant de modifier l’exploitation.", "Voertuigen en weginfrastructuur werken als één servicesysteem. Capaciteit, toegankelijkheid en lokale omstandigheden sturen de opdrachten.\nEen gedeelde simulatie laat operatoren afwegingen onderzoeken vóór de straatwerking verandert."), img.projectCorridor, { category: "Corridor blueprint", sector: "Connected Infrastructure", client: "Mobility authorities and operators", date: "2026", featured: true, displayOrder: 3, tags: ["infrastructure", "accessibility", "simulation"], relatedIds: ["motion-os", "mobility-twin"] }),
];

const news: ContentItem[] = [
  item("introducing-movera", "news", t("Introducing MOVERA", "هذه هي موفيرا", "MOVERA entre en mouvement", "MOVERA komt in beweging"), t("A Belgian platform for the decisions behind autonomous and connected mobility.", "منصة بلجيكية للقرارات التي تقود التنقل الذاتي والمتصل.", "Une plateforme belge dédiée aux décisions qui font avancer la mobilité autonome et connectée.", "Een Belgisch platform voor de beslissingen achter autonome en verbonden mobiliteit."), t("Intelligent mobility only matters when operators, engineers and passengers understand what the system is doing.\nMOVERA connects vehicle perception, fleet operations and human judgment for real Belgian mobility conditions.", "لا قيمة للتنقل الذكي ما لم يفهم المشغّلون والمهندسون والركاب ما يفعله النظام.\nتربط موفيرا إدراك المركبة بعمليات الأسطول والحكم البشري ضمن واقع التنقل في بلجيكا.", "La mobilité intelligente n’a de valeur que si opérateurs, ingénieurs et passagers comprennent le système.\nMOVERA relie perception véhicule, opérations de flotte et jugement humain pour les réalités belges.", "Intelligente mobiliteit telt pas wanneer operatoren, ingenieurs en passagiers begrijpen wat het systeem doet.\nMOVERA verbindt voertuigperceptie, vlootoperaties en menselijk oordeel voor de Belgische mobiliteitsrealiteit."), img.newsIntro, { category: "Company", date: "2026-08-19", featured: true, displayOrder: 0, tags: ["MOVERA", "Belgium", "mobility"] }),
  item("edge-intelligence-near-movement", "news", t("Intelligence belongs near movement", "الذكاء الأقرب إلى الحركة", "L’intelligence au plus près du mouvement", "Intelligentie dicht bij de beweging"), t("Why useful vehicle intelligence combines edge response with accountable operations.", "لماذا يجمع ذكاء المركبة بين الاستجابة الطرفية والعمليات الخاضعة للمساءلة.", "Pourquoi l’intelligence véhicule associe réaction locale et opérations responsables.", "Waarom voertuigintelligentie lokale respons koppelt aan verantwoordelijke operaties."), t("Fast vehicle decisions belong close to the sensor; service decisions still need context, ownership and evidence.\nMOVERA keeps the response local where latency matters and shared where accountability matters.", "تُتخذ قرارات المركبة السريعة بالقرب من المستشعر، بينما تحتاج قرارات الخدمة إلى السياق والمسؤولية والدليل.\nتُبقي موفيرا الاستجابة محلية عندما يهم الزمن ومشتركة عندما تهم المساءلة.", "Les décisions rapides restent proches du capteur; les décisions de service exigent contexte, responsabilité et preuve.\nMOVERA garde la réponse locale quand la latence compte et partagée quand la responsabilité compte.", "Snelle voertuigbeslissingen horen dicht bij de sensor; servicebeslissingen vragen context, eigenaarschap en bewijs.\nMOVERA houdt respons lokaal waar latency telt en gedeeld waar verantwoordelijkheid telt."), img.newsEdge, { category: "Technology", date: "2026-08-12", featured: true, displayOrder: 1, tags: ["edge", "operations", "accountability"] }),
  item("belgium-shared-mobility-language", "news", t("Belgium needs a shared mobility language", "بلجيكا تحتاج لغة مشتركة للتنقل", "La Belgique a besoin d’un langage commun de la mobilité", "België heeft een gedeelde mobiliteitstaal nodig"), t("Vehicles, authorities and operators move better when service meaning is shared.", "تتحرك المركبات والجهات العامة والمشغّلون بكفاءة أكبر عندما تتوحد معاني الخدمة.", "Véhicules, autorités et opérateurs avancent mieux lorsqu’ils partagent le sens du service.", "Voertuigen, overheden en operatoren werken beter wanneer servicetaal gedeeld is."), t("Belgian regions and transport modes bring different systems and responsibilities to the same journey. A shared operational language reduces friction without erasing local context.\nMOVERA structures missions, exceptions and evidence so each partner keeps its role while collaborating on the same movement.", "تجمع الرحلة في بلجيكا أنظمة ومسؤوليات مختلفة بين المناطق ووسائل النقل. تقلل اللغة التشغيلية المشتركة الاحتكاك من دون إلغاء السياق المحلي.\nتنظم موفيرا المهام والاستثناءات والأدلة بحيث يحافظ كل طرف على دوره ويتعاون الجميع حول الحركة نفسها.", "Les régions et modes belges apportent des systèmes et responsabilités différents à un même trajet. Un langage commun réduit les frictions sans effacer le contexte local.\nMOVERA structure missions, exceptions et preuves afin que chaque partenaire garde son rôle.", "Belgische regio’s en vervoersmodi brengen verschillende systemen en verantwoordelijkheden samen. Een gedeelde taal vermindert wrijving zonder lokale context te wissen.\nMOVERA structureert opdrachten, uitzonderingen en bewijs zodat elke partner zijn rol behoudt."), img.newsBelgium, { category: "Belgium", date: "2026-08-05", featured: true, displayOrder: 2, tags: ["Belgium", "interoperability", "partnership"] }),
];

const blogs: ContentItem[] = [
  item("designing-operator-confidence", "blogs", t("Designing operator confidence", "كيف نصمم ثقة المشغّل", "Concevoir la confiance de l’opérateur", "Operatorvertrouwen ontwerpen"), t("A clear exception is more useful than a crowded real-time dashboard.", "الاستثناء الواضح أنفع من لوحة حية مزدحمة.", "Une exception claire vaut mieux qu’un tableau de bord surchargé.", "Een duidelijke uitzondering is waardevoller dan een druk dashboard."), t("Operator confidence comes from knowing what changed, how certain the system is and which action remains available.\nNormal movement stays quiet; uncertainty appears with evidence; irreversible actions ask for deliberate confirmation.", "تأتي ثقة المشغّل من معرفة ما تغيّر ومدى يقين النظام وما الإجراءات المتاحة.\nتبقى الحركة الطبيعية هادئة، ويظهر عدم اليقين مع دليله، وتتطلب الإجراءات غير القابلة للتراجع تأكيداً مقصوداً.", "La confiance vient de la compréhension du changement, du niveau de certitude et des actions possibles.\nLe normal reste discret, l’incertitude arrive avec sa preuve et l’irréversible demande une confirmation délibérée.", "Vertrouwen komt van begrijpen wat wijzigde, hoe zeker het systeem is en welke actie mogelijk blijft.\nNormale beweging blijft stil, onzekerheid verschijnt met bewijs en onomkeerbare acties vragen bewuste bevestiging."), img.blogOperator, { category: "Operations design", date: "2026-08-16", featured: true, displayOrder: 0, tags: ["operators", "exceptions", "human factors"] }),
  item("trust-before-boarding", "blogs", t("Trust begins before boarding", "الثقة تبدأ قبل الصعود", "La confiance commence avant l’embarquement", "Vertrouwen begint vóór het instappen"), t("Autonomous journeys need a service language passengers recognise before the doors open.", "تحتاج الرحلات الذاتية إلى لغة خدمة يفهمها الراكب قبل أن تُفتح الأبواب.", "Un trajet autonome a besoin d’un langage compris avant l’ouverture des portes.", "Een autonome rit heeft servicetaal nodig die reizigers herkennen vóór de deuren openen."), t("People judge a service through arrival, identity, accessibility and support before they inspect the technology. Those cues should stay consistent from stop to cabin.\nWhen a route changes or the vehicle asks for help, the same language must explain why and what happens next.", "يقيّم الناس الخدمة من طريقة الوصول والهوية وسهولة الاستخدام والدعم قبل التفكير في التقنية. يجب أن تبقى هذه الإشارات متسقة من المحطة إلى المقصورة.\nعندما يتغير المسار أو تطلب المركبة مساعدة، ينبغي للغة نفسها أن تشرح السبب والخطوة التالية.", "Les personnes jugent un service par son arrivée, son identité, son accessibilité et son assistance avant la technologie. Ces repères restent cohérents de l’arrêt à l’habitacle.\nSi la route change ou si le véhicule demande de l’aide, le même langage explique pourquoi et ce qui suit.", "Mensen beoordelen een dienst op aankomst, herkenbaarheid, toegankelijkheid en ondersteuning vóór de technologie. Die signalen blijven van halte tot cabine consistent.\nWanneer de route wijzigt of het voertuig hulp vraagt, legt dezelfde taal uit waarom en wat volgt."), img.blogTrust, { category: "Passenger experience", date: "2026-08-09", featured: true, displayOrder: 1, tags: ["trust", "accessibility", "service design"] }),
  item("from-signals-to-decisions", "blogs", t("From signals to decisions", "من الإشارات إلى القرارات", "Des signaux aux décisions", "Van signalen naar beslissingen"), t("The useful unit of mobility intelligence is not a prediction. It is a better decision.", "وحدة القيمة في ذكاء التنقل ليست التنبؤ، بل القرار الأفضل.", "L’unité utile de l’intelligence mobilité n’est pas la prédiction, mais la meilleure décision.", "De nuttige eenheid van mobiliteitsintelligentie is geen voorspelling, maar een betere beslissing."), t("A signal becomes operational intelligence only with context, confidence, consequence and an owner. Without those elements, more data creates more monitoring work.\nMOVERA shows where automation helps, where policy applies and where a person must decide.", "لا تصبح الإشارة ذكاءً تشغيلياً إلا مع السياق ودرجة الثقة والأثر وصاحب القرار. من دون ذلك، تزيد البيانات عبء المراقبة.\nتوضح موفيرا أين تفيد الأتمتة، وأين تُطبّق السياسة، وأين يجب أن يحسم الإنسان.", "Un signal devient intelligence opérationnelle avec contexte, confiance, conséquence et responsable. Sans eux, davantage de données signifie davantage de surveillance.\nMOVERA montre où l’automatisation aide, où la règle s’applique et où une personne décide.", "Een signaal wordt operationele intelligentie met context, vertrouwen, gevolg en een eigenaar. Zonder die elementen zorgt meer data voor meer monitoring.\nMOVERA toont waar automatisering helpt, beleid geldt en een mens beslist."), img.blogSignals, { category: "Mobility intelligence", date: "2026-08-02", featured: true, displayOrder: 2, tags: ["decisions", "evidence", "governance"] }),
];

const innovation: ContentItem[] = [
  item("confidence-maps", "innovation", t("Confidence Maps", "خرائط الثقة", "Cartes de confiance", "Vertrouwenskaarten"), t("Show where vehicle perception is strong, uncertain or changing.", "نوضح أين يكون إدراك المركبة قوياً أو متردداً أو متغيراً.", "Montrer où la perception est solide, incertaine ou changeante.", "Toon waar voertuigperceptie sterk, onzeker of veranderlijk is."), t("Confidence Maps combines environmental context, model confidence and review evidence without pretending uncertainty has disappeared.\nThe research supports safer testing, sharper annotation and better release decisions.", "تجمع خرائط الثقة السياق البيئي وثقة النموذج وأدلة المراجعة من دون الادعاء بأن عدم اليقين اختفى.\nويدعم البحث اختبارات أكثر أماناً وتعليقات أدق وقرارات إطلاق أفضل.", "Confidence Maps associe contexte, confiance du modèle et preuves de revue sans masquer l’incertitude.\nLa recherche soutient des essais plus sûrs, une annotation plus précise et de meilleures décisions.", "Confidence Maps combineert omgevingscontext, modelvertrouwen en reviewbewijs zonder onzekerheid weg te poetsen.\nHet onderzoek ondersteunt veiliger testen, scherpere annotatie en betere vrijgavebeslissingen."), img.innovationConfidence, { category: "Applied research", sector: "Autonomous Vehicles", featured: true, displayOrder: 0, tags: ["confidence", "perception", "validation"] }),
  item("mobility-simulation-studio", "innovation", t("Mobility Simulation Studio", "استوديو محاكاة التنقل", "Studio de simulation mobilité", "Mobiliteitssimulatiestudio"), t("Rehearse service changes before people and vehicles meet them on the street.", "نختبر تغييرات الخدمة قبل أن يواجهها الناس والمركبات في الشارع.", "Répéter les changements de service avant leur arrivée dans la rue.", "Beproef servicewijzigingen vóór mensen en voertuigen ze op straat ervaren."), t("Planners, operators, engineers and designers inspect the same scenarios together. Demand, incidents, accessibility and fleet constraints become visible trade-offs.\nThe goal is a disciplined environment for making better decisions earlier.", "يفحص المخططون والمشغّلون والمهندسون والمصممون السيناريوهات نفسها معاً. فتتحول متطلبات الطلب والحوادث وسهولة الوصول وقيود الأسطول إلى مفاضلات واضحة.\nالهدف بيئة منضبطة لاتخاذ قرارات أفضل في وقت أبكر.", "Planificateurs, opérateurs, ingénieurs et designers examinent les mêmes scénarios. Demande, incidents, accessibilité et contraintes deviennent des arbitrages visibles.\nL’objectif est un cadre rigoureux pour mieux décider plus tôt.", "Planners, operatoren, ingenieurs en ontwerpers onderzoeken dezelfde scenario’s. Vraag, incidenten, toegankelijkheid en vlootbeperkingen worden zichtbare afwegingen.\nHet doel is een gedisciplineerde omgeving om vroeger beter te beslissen."), img.innovationSimulation, { category: "Simulation", sector: "Mobility Planning", featured: true, displayOrder: 1, tags: ["simulation", "planning", "collaboration"] }),
  item("curb-intelligence", "innovation", t("Curb Intelligence", "ذكاء حافة الطريق", "Intelligence du bord de voirie", "Intelligente stoeprand"), t("Study the street decisions that shape access, safety and service reliability.", "ندرس قرارات الشارع التي تصنع سهولة الوصول والسلامة وموثوقية الخدمة.", "Étudier les décisions de voirie qui façonnent accès, sécurité et fiabilité.", "Onderzoek straatbeslissingen die toegang, veiligheid en betrouwbaarheid bepalen."), t("Pick-up space, deliveries, cycles and accessible boarding compete at the same kerb. Live context and clear service rules can reduce conflict.\nPublic-space outcomes stay visible alongside vehicle efficiency.", "تتنافس مساحة الصعود والتوصيل والدراجات والصعود المهيأ على الحافة نفسها. يمكن للسياق الحي وقواعد الخدمة الواضحة أن تقلل التعارض.\nيبقى أثر الحل على الفضاء العام ظاهراً إلى جانب كفاءة المركبات.", "Prise en charge, livraisons, vélos et embarquement accessible partagent le même bord de voirie. Le contexte en direct et des règles claires réduisent les conflits.\nLes résultats pour l’espace public restent visibles avec l’efficacité des véhicules.", "Oppikken, leveringen, fietsen en toegankelijk instappen delen dezelfde stoeprand. Live context en duidelijke regels verminderen conflicten.\nDe uitkomst voor de publieke ruimte blijft even zichtbaar als voertuigefficiëntie."), img.innovationCurb, { category: "Street research", sector: "Connected Infrastructure", featured: true, displayOrder: 2, tags: ["curb", "accessibility", "public space"] }),
];

const jobs: ContentItem[] = [
  item("autonomy-systems-engineer", "jobs", t("Autonomy Systems Engineer", "مهندس أنظمة القيادة الذاتية", "Ingénieur·e systèmes autonomes", "Autonomy Systems Engineer"), t("Turn perception and planning behaviour into testable vehicle evidence.", "حوّل سلوك الإدراك والتخطيط إلى أدلة قابلة للاختبار على المركبة.", "Transformer perception et planification en preuves vérifiables sur véhicule.", "Zet perceptie- en planningsgedrag om in testbaar voertuigbewijs."), t("Connect vehicle software, sensor context and road-test workflows. Move between system behaviour, field evidence and clear technical decisions.\nWork with product, safety and operations colleagues in Belgium to make difficult autonomy moments reproducible.", "اربط برمجيات المركبة بسياق المستشعرات ومسارات الاختبار الميداني، وانتقل بين سلوك النظام والدليل العملي والقرار التقني الواضح.\nاعمل مع فرق المنتج والسلامة والعمليات في بلجيكا لجعل المواقف الصعبة قابلة للتكرار.", "Reliez logiciel véhicule, contexte capteur et parcours d’essai. Passez du comportement système à la preuve terrain et à la décision claire.\nTravaillez avec produit, sécurité et opérations en Belgique pour rendre les situations difficiles reproductibles.", "Verbind voertuigsoftware, sensorcontext en wegtestflows. Schakel tussen systeemgedrag, veldbewijs en heldere technische beslissingen.\nWerk met product-, safety- en operationele collega’s in België om moeilijke momenten reproduceerbaar te maken."), img.careersTeam, { category: "Engineering", region: "hub-a", displayOrder: 0, tags: ["hybrid", "Belgium", "autonomy"] }),
  item("mobility-data-engineer", "jobs", t("Mobility Data Engineer", "مهندس بيانات التنقل", "Ingénieur·e data mobilité", "Mobility Data Engineer"), t("Build the signal layer behind fleet, vehicle and street decisions.", "ابنِ طبقة الإشارات خلف قرارات الأسطول والمركبة والشارع.", "Construire la couche de signaux derrière les décisions de flotte, véhicule et voirie.", "Bouw de signaallaag achter vloot-, voertuig- en straatbeslissingen."), t("Shape event models, quality controls and data products trusted by operators and engineers. The work spans streaming signals, operational context and review evidence.\nWe value thoughtful modelling, observability and plain explanations over clever pipelines understood by one person.", "صمّم نماذج الأحداث وضوابط الجودة ومنتجات البيانات التي يثق بها المشغّلون والمهندسون. ويشمل العمل الإشارات المتدفقة والسياق التشغيلي وأدلة المراجعة.\nنقدّر النمذجة المتأنية وقابلية الرصد والشرح المباشر أكثر من مسارات لا يفهمها سوى شخص واحد.", "Façonnez modèles d’événements, contrôles qualité et produits data fiables. Le travail couvre flux de signaux, contexte opérationnel et preuves.\nNous privilégions une modélisation réfléchie, l’observabilité et des explications simples aux pipelines compris par une seule personne.", "Vorm eventmodellen, kwaliteitscontroles en dataproducten die operatoren en ingenieurs vertrouwen. Het werk omvat streamingsignalen, context en reviewbewijs.\nWe waarderen doordachte modellering, observeerbaarheid en duidelijke uitleg boven pipelines die maar één persoon begrijpt."), img.careersData, { category: "Data", region: "hub-b", displayOrder: 1, tags: ["hybrid", "Belgium", "data"] }),
  item("systems-integration-lead", "jobs", t("Systems Integration Lead", "قائد تكامل الأنظمة", "Responsable intégration systèmes", "Lead Systeemintegratie"), t("Coordinate the interfaces, evidence and people behind an end-to-end mobility service.", "نسّق الواجهات والأدلة والفرق خلف خدمة تنقل متكاملة.", "Coordonner interfaces, preuves et équipes pour un service de bout en bout.", "Coördineer interfaces, bewijs en mensen achter een end-to-end mobiliteitsdienst."), t("Lead integration across vehicles, cloud services, operator workflows and roadside systems. Turn cross-team ambiguity into an executable test plan.\nBring calm structure to complex programmes and communicate with engineers, service owners and partners.", "تولَّ قيادة التكامل بين المركبات والخدمات السحابية ومسارات المشغّلين وأنظمة الطريق، وحوّل الغموض بين الفرق إلى خطة اختبار قابلة للتنفيذ.\nامنح البرامج المعقدة هيكلاً هادئاً وتواصل مع المهندسين ومالكي الخدمات والشركاء.", "Pilotez l’intégration entre véhicules, services cloud, parcours opérateurs et systèmes routiers. Transformez l’ambiguïté en plan d’essai exécutable.\nApportez une structure sereine aux programmes complexes et dialoguez avec ingénieurs, responsables et partenaires.", "Leid integratie tussen voertuigen, clouddiensten, operatorflows en wegsystemen. Zet onduidelijkheid om in een uitvoerbaar testplan.\nBreng rustige structuur in complexe programma’s en communiceer met engineers, service-eigenaars en partners."), img.careersIntegration, { category: "Delivery", region: "hub-c", displayOrder: 2, tags: ["hybrid", "Belgium", "integration"] }),
];

const aboutPagesSeed: ContentItem[] = [
  page("who-we-are", t("Who we are", "من نحن", "Qui sommes-nous", "Wie we zijn"), t("A Belgian mobility platform built around clear, accountable movement.", "منصة تنقل بلجيكية تُبنى حول حركة واضحة وخاضعة للمساءلة.", "Une plateforme belge de mobilité fondée sur des mouvements clairs et responsables.", "Een Belgisch mobiliteitsplatform voor duidelijke, verantwoorde beweging."), t("MOVERA brings vehicle engineering, operations, service design and applied intelligence into one team. We focus on the decisions that connect a capable vehicle to a dependable mobility service.", "تجمع موفيرا هندسة المركبات والعمليات وتصميم الخدمات والذكاء التطبيقي ضمن فريق واحد. نركز على القرارات التي تربط مركبة قادرة بخدمة تنقل يمكن الاعتماد عليها.", "MOVERA réunit ingénierie véhicule, opérations, design de service et intelligence appliquée. Nous travaillons sur les décisions qui relient un véhicule capable à un service fiable.", "MOVERA brengt voertuigengineering, operaties, serviceontwerp en toegepaste intelligentie samen. We focussen op de beslissingen die een bekwaam voertuig verbinden met een betrouwbare dienst."), img.aboutStudio, { aboutLayout: "story", displayOrder: 0, sections: [section("purpose", t("Movement people can understand", "حركة يفهمها الناس", "Un mouvement que chacun comprend", "Beweging die mensen begrijpen"), t("We make system state, uncertainty and responsibility visible to the people who operate and use mobility services.", "نجعل حالة النظام وعدم اليقين والمسؤولية واضحة لمن يشغّلون خدمات التنقل ويستخدمونها.", "Nous rendons l’état du système, l’incertitude et la responsabilité visibles pour celles et ceux qui opèrent et utilisent la mobilité.", "We maken systeemstatus, onzekerheid en verantwoordelijkheid zichtbaar voor wie mobiliteitsdiensten uitbaat en gebruikt.")), section("method", t("Evidence before theatre", "الدليل قبل الاستعراض", "La preuve avant le spectacle", "Bewijs vóór spektakel"), t("We prefer measurable service behaviour, traceable decisions and calm interfaces to technology that merely looks advanced.", "نفضّل سلوك الخدمة القابل للقياس والقرارات القابلة للتتبع والواجهات الهادئة على تقنية تبدو متقدمة بلا أثر حقيقي.", "Nous préférons un service mesurable, des décisions traçables et des interfaces sereines à une technologie seulement spectaculaire.", "We kiezen voor meetbaar servicegedrag, traceerbare beslissingen en rustige interfaces boven technologie die alleen geavanceerd oogt."))] }),
  page("history", t("How MOVERA moves", "كيف تتقدم موفيرا", "Le mouvement MOVERA", "Hoe MOVERA beweegt"), t("A company shaped by vehicle craft, operational evidence and Belgian mobility complexity.", "شركة تصوغها خبرة المركبات والدليل التشغيلي وتعقيد التنقل في بلجيكا.", "Une entreprise façonnée par le savoir-faire véhicule, la preuve opérationnelle et la complexité belge.", "Een bedrijf gevormd door voertuigvakmanschap, operationeel bewijs en Belgische mobiliteitscomplexiteit."), t("MOVERA follows a clear progression: observe the movement, understand the decision, coordinate the service and learn from evidence.", "تسير موفيرا في تسلسل واضح: نرصد الحركة، ونفهم القرار، وننسق الخدمة، ثم نتعلم من الدليل.", "MOVERA suit une progression simple : observer le mouvement, comprendre la décision, coordonner le service et apprendre de la preuve.", "MOVERA volgt een heldere lijn: beweging waarnemen, de beslissing begrijpen, de dienst coördineren en leren uit bewijs."), img.aboutHistory, { aboutLayout: "timeline", displayOrder: 1, timeline: [
    { id: "observe", label: t("01 · Observe", "01 · نرصد", "01 · Observer", "01 · Waarnemen"), title: t("Start with the real street", "نبدأ من الشارع الحقيقي", "Commencer dans la vraie rue", "Begin bij de echte straat"), body: t("Ground every product decision in conditions vehicles, operators and passengers actually meet.", "نربط كل قرار منتج بالظروف التي تواجهها المركبات والمشغّلون والركاب فعلاً.", "Ancrer chaque décision produit dans les conditions réellement rencontrées.", "Veranker elke productbeslissing in de omstandigheden die voertuigen, operatoren en passagiers echt ervaren."), media: img.aboutHistory },
    { id: "decide", label: t("02 · Decide", "02 · نقرر", "02 · Décider", "02 · Beslissen"), title: t("Build the decision layer", "نبني طبقة القرار", "Construire la couche de décision", "Bouw de beslislaag"), body: t("Connect perception, service rules and human authority so movement can scale responsibly.", "نربط الإدراك وقواعد الخدمة والقرار البشري كي تتوسع الحركة بمسؤولية.", "Relier perception, règles de service et autorité humaine pour grandir de manière responsable.", "Verbind perceptie, serviceregels en menselijke bevoegdheid zodat beweging verantwoord kan opschalen."), media: img.productCommand },
    { id: "learn", label: t("03 · Learn", "03 · نتعلم", "03 · Apprendre", "03 · Leren"), title: t("Make mobility learn", "نجعل التنقل يتعلم", "Faire apprendre la mobilité", "Laat mobiliteit leren"), body: t("Turn verified operational evidence into safer systems and stronger services.", "نحوّل الدليل التشغيلي الموثق إلى أنظمة أكثر أماناً وخدمات أقوى.", "Transformer les preuves vérifiées en systèmes plus sûrs et services plus solides.", "Zet gevalideerd operationeel bewijs om in veiligere systemen en sterkere diensten."), media: img.innovationConfidence },
  ] }),
  page("vision-mission", t("Vision and mission", "الرؤية والرسالة", "Vision et mission", "Visie en missie"), t("Move intelligence into the real world without losing human understanding.", "ننقل الذكاء إلى العالم الحقيقي من دون أن نفقد وضوحه للإنسان.", "Mettre l’intelligence en mouvement sans perdre la compréhension humaine.", "Breng intelligentie naar de echte wereld zonder menselijk begrip te verliezen."), t("Our vision is mobility that feels more capable because it is easier to understand, operate and trust. Our mission is to build the systems and working practices that make that possible.", "رؤيتنا تنقل أكثر قدرة لأنه أسهل فهماً وتشغيلاً وثقة. ورسالتنا بناء الأنظمة وأساليب العمل التي تحقق ذلك.", "Notre vision : une mobilité plus capable parce qu’elle est plus simple à comprendre, opérer et croire. Notre mission : construire les systèmes et pratiques qui la rendent possible.", "Onze visie is mobiliteit die meer kan omdat ze eenvoudiger te begrijpen, bedienen en vertrouwen is. Onze missie is de systemen en werkwijzen bouwen die dat mogelijk maken."), img.innovationSimulation, { aboutLayout: "vision", displayOrder: 2, sections: [section("vision", t("Vision", "الرؤية", "Vision", "Visie"), t("A connected ecosystem where every important movement can be understood and improved.", "منظومة متصلة يمكن فهم كل حركة مهمة فيها وتحسينها.", "Un écosystème connecté où chaque mouvement important peut être compris et amélioré.", "Een verbonden ecosysteem waarin elke belangrijke beweging begrepen en verbeterd kan worden.")), section("mission", t("Mission", "الرسالة", "Mission", "Missie"), t("Give vehicle teams and operators one accountable path from signal to decision.", "نمنح فرق المركبات والمشغّلين مساراً واحداً خاضعاً للمساءلة من الإشارة إلى القرار.", "Donner aux équipes véhicule et aux opérateurs un chemin responsable du signal à la décision.", "Geef voertuigteams en operatoren één verantwoord pad van signaal naar beslissing."))] }),
  page("clients-certificates", t("Partnership and assurance", "الشراكة والضمان", "Partenariats et assurance", "Partnerschap en zekerheid"), t("A practical framework for working across vehicles, infrastructure, operations and public space.", "إطار عملي للتعاون بين المركبات والبنية التحتية والعمليات والفضاء العام.", "Un cadre concret pour collaborer entre véhicules, infrastructure, opérations et espace public.", "Een praktisch kader voor samenwerking tussen voertuigen, infrastructuur, operaties en publieke ruimte."), t("MOVERA builds partnerships around explicit roles, shared evidence and traceable decisions. Assurance grows from how work is governed, tested and operated.", "تبني موفيرا شراكاتها على أدوار صريحة وأدلة مشتركة وقرارات قابلة للتتبع. وينشأ الضمان من طريقة إدارة العمل واختباره وتشغيله.", "MOVERA fonde ses partenariats sur des rôles explicites, des preuves partagées et des décisions traçables. L’assurance vient de la gouvernance, des essais et de l’exploitation.", "MOVERA bouwt partnerschappen rond expliciete rollen, gedeeld bewijs en traceerbare beslissingen. Zekerheid groeit uit de manier waarop werk bestuurd, getest en uitgebaat wordt."), img.newsBelgium, { aboutLayout: "certificates", displayOrder: 3, credentials: [
    { id: "shared-evidence", title: t("Shared evidence", "دليل مشترك", "Preuve partagée", "Gedeeld bewijs"), issuer: t("Delivery practice", "منهج التنفيذ", "Pratique de réalisation", "Realisatiepraktijk"), description: t("Partners work from agreed tests, decision records and service outcomes.", "يعمل الشركاء انطلاقاً من اختبارات متفق عليها وسجلات قرار ونتائج خدمة واضحة.", "Les partenaires s’appuient sur des essais convenus, des traces de décision et des résultats de service.", "Partners werken met afgesproken tests, beslisregistraties en service-uitkomsten."), media: img.newsBelgium },
    { id: "responsible-automation", title: t("Responsible automation", "أتمتة مسؤولة", "Automatisation responsable", "Verantwoorde automatisering"), issuer: t("Operating principle", "مبدأ تشغيلي", "Principe opérationnel", "Operationeel principe"), description: t("Automation has visible limits, escalation paths and human authority.", "للأتمتة حدود واضحة ومسارات تصعيد وسلطة بشرية معروفة.", "L’automatisation possède des limites visibles, des voies d’escalade et une autorité humaine.", "Automatisering heeft zichtbare grenzen, escalatiepaden en menselijke bevoegdheid."), media: img.innovationConfidence },
  ] }),
  page("ceo-message", t("Leadership note", "رسالة القيادة", "Message de la direction", "Boodschap van het leiderschap"), t("Why MOVERA puts understanding at the centre of intelligent movement.", "لماذا تضع موفيرا الفهم في قلب الحركة الذكية.", "Pourquoi MOVERA place la compréhension au cœur du mouvement intelligent.", "Waarom MOVERA begrip centraal stelt in intelligente beweging."), t("Mobility earns trust when capability and responsibility move together.", "يكسب التنقل الثقة عندما تتقدم القدرة والمسؤولية معاً.", "La mobilité gagne la confiance lorsque capacité et responsabilité avancent ensemble.", "Mobiliteit verdient vertrouwen wanneer vermogen en verantwoordelijkheid samen bewegen."), img.projectBrussels, { displayOrder: 4 }),
  page("leadership", t("Leadership", "القيادة", "Direction", "Leiderschap"), t("Disciplines that hold product ambition, engineering evidence and service responsibility together.", "تخصصات تجمع طموح المنتج والدليل الهندسي ومسؤولية الخدمة.", "Des disciplines qui relient ambition produit, preuve d’ingénierie et responsabilité de service.", "Disciplines die productambitie, engineeringbewijs en serviceverantwoordelijkheid samenhouden."), t("MOVERA is led through complementary responsibilities rather than personality profiles. Direction remains close to engineering, operations and the people who experience the service.", "تُقاد موفيرا عبر مسؤوليات متكاملة لا عبر صور فردية. وتبقى القيادة قريبة من الهندسة والعمليات ومن الناس الذين يعيشون الخدمة.", "MOVERA est dirigée par des responsabilités complémentaires plutôt que par des profils individuels. La direction reste proche de l’ingénierie, des opérations et des personnes qui vivent le service.", "MOVERA wordt geleid vanuit complementaire verantwoordelijkheden, niet vanuit persoonsprofielen. De leiding blijft dicht bij engineering, operaties en de mensen die de dienst ervaren."), img.careersTeam, { aboutLayout: "leadership", displayOrder: 5, profiles: [
    { id: "strategy", name: t("Mobility Strategy", "استراتيجية التنقل", "Stratégie mobilité", "Mobiliteitsstrategie"), role: t("Direction and partnerships", "الاتجاه والشراكات", "Direction et partenariats", "Richting en partnerschappen"), summary: t("Connects public value, service intent and a clear route to deployment.", "تربط القيمة العامة بهدف الخدمة ومسار واضح للتطبيق.", "Relie valeur publique, intention de service et chemin de déploiement.", "Verbindt publieke waarde, service-intentie en een helder implementatiepad."), portrait: img.careersTeam },
    { id: "engineering", name: t("Autonomy Engineering", "هندسة القيادة الذاتية", "Ingénierie autonome", "Autonomie-engineering"), role: t("Systems and evidence", "الأنظمة والأدلة", "Systèmes et preuves", "Systemen en bewijs"), summary: t("Turns perception and vehicle behaviour into testable, accountable systems.", "تحوّل الإدراك وسلوك المركبة إلى أنظمة قابلة للاختبار والمساءلة.", "Transforme perception et comportement véhicule en systèmes testables et responsables.", "Zet perceptie en voertuiggedrag om in testbare, verantwoordelijke systemen."), portrait: img.careersIntegration },
    { id: "operations", name: t("Product Operations", "عمليات المنتج", "Opérations produit", "Productoperaties"), role: t("Service and experience", "الخدمة والتجربة", "Service et expérience", "Service en ervaring"), summary: t("Keeps operator workflows, passenger experience and product decisions aligned.", "تُبقي مسارات المشغّلين وتجربة الركاب وقرارات المنتج في اتجاه واحد.", "Aligne parcours opérateurs, expérience passager et décisions produit.", "Houdt operatorflows, passagierservaring en productbeslissingen op één lijn."), portrait: img.blogOperator },
  ] }),
];

const aboutCoverOverrides: Partial<Record<string, NonNullable<ContentItem["cover"]>>> = {
  "vision-mission": img.aboutVision,
  "clients-certificates": img.aboutAssurance,
  "ceo-message": img.aboutLeadershipNote,
  leadership: img.aboutLeadership,
};

const aboutPages: ContentItem[] = aboutPagesSeed.map(pageItem => ({
  ...pageItem,
  cover: aboutCoverOverrides[pageItem.id] ?? pageItem.cover,
}));

const legalPages: ContentItem[] = [
  page("privacy-policy", t("Privacy policy", "سياسة الخصوصية", "Politique de confidentialité", "Privacybeleid"), t("How MOVERA handles personal information across this website.", "كيف تتعامل موفيرا مع المعلومات الشخصية عبر هذا الموقع.", "Comment MOVERA traite les données personnelles sur ce site.", "Hoe MOVERA persoonsgegevens op deze website verwerkt."), t("Effective 19 August 2026. This notice covers website contact, newsletter, career application and assistant interactions.", "سارية من 19 أغسطس 2026. تغطي هذه السياسة التواصل والنشرة البريدية وطلبات الوظائف والتفاعل مع المساعد.", "En vigueur le 19 août 2026. Cette notice couvre le contact, la lettre d’information, les candidatures et l’assistant.", "Geldig vanaf 19 augustus 2026. Dit beleid geldt voor contact, nieuwsbrief, sollicitaties en assistentinteracties."), undefined, { displayOrder: 6, sections: [
    section("data", t("Information we receive", "المعلومات التي نستقبلها", "Informations reçues", "Gegevens die we ontvangen"), t("When you contact us, subscribe, apply or use the assistant, we receive the details you submit and technical information needed to protect and operate the service.", "عندما تتواصل معنا أو تشترك أو تتقدم لوظيفة أو تستخدم المساعد، نستقبل البيانات التي ترسلها والمعلومات التقنية اللازمة لحماية الخدمة وتشغيلها.", "Lorsque vous nous contactez, vous inscrivez, postulez ou utilisez l’assistant, nous recevons les informations transmises et les données techniques nécessaires au service.", "Wanneer u contact opneemt, inschrijft, solliciteert of de assistent gebruikt, ontvangen we de verstrekte gegevens en technische informatie die nodig is voor de dienst.")),
    section("purpose", t("Why we use it", "لماذا نستخدمها", "Pourquoi nous les utilisons", "Waarom we ze gebruiken"), t("We answer requests, deliver chosen communications, assess applications, maintain security and improve reliability. We do not sell personal information.", "نستخدم المعلومات للرد على الطلبات وتقديم الرسائل المختارة وتقييم الوظائف والحفاظ على الأمن وتحسين الموثوقية. ولا نبيع المعلومات الشخصية.", "Nous répondons aux demandes, fournissons les communications choisies, examinons les candidatures, assurons la sécurité et améliorons la fiabilité. Nous ne vendons pas de données personnelles.", "We beantwoorden vragen, leveren gekozen communicatie, beoordelen sollicitaties, bewaken beveiliging en verbeteren betrouwbaarheid. We verkopen geen persoonsgegevens.")),
    section("rights", t("Your choices and rights", "خياراتك وحقوقك", "Vos choix et vos droits", "Uw keuzes en rechten"), t("Depending on the circumstances, you may ask for access, correction, deletion, restriction, portability or object to processing. You can withdraw newsletter consent at any time. Contact hello@movera.ai.", "بحسب الظروف، يمكنك طلب الاطلاع أو التصحيح أو الحذف أو تقييد المعالجة أو نقل البيانات أو الاعتراض. ويمكنك سحب موافقة النشرة في أي وقت. راسل hello@movera.ai.", "Selon la situation, vous pouvez demander accès, rectification, effacement, limitation, portabilité ou vous opposer au traitement. Le consentement à la lettre peut être retiré à tout moment. Contact : hello@movera.ai.", "Afhankelijk van de situatie kunt u toegang, verbetering, verwijdering, beperking of overdraagbaarheid vragen, of bezwaar maken. Nieuwsbrieftoestemming kunt u altijd intrekken. Contact: hello@movera.ai.")),
    section("retention", t("Retention and contact", "الاحتفاظ والتواصل", "Conservation et contact", "Bewaring en contact"), t("We retain information only as long as needed for the stated purpose, legal duties and security. Service providers act under appropriate instructions. Questions can be sent to hello@movera.ai.", "نحتفظ بالمعلومات بقدر ما يلزم للغرض المعلن والالتزامات القانونية والأمن. ويعمل مقدمو الخدمة وفق تعليمات مناسبة. أرسل أسئلتك إلى hello@movera.ai.", "Nous conservons les données pendant la durée nécessaire à la finalité, aux obligations légales et à la sécurité. Nos prestataires agissent sur instruction. Contact : hello@movera.ai.", "We bewaren gegevens niet langer dan nodig voor het doel, wettelijke plichten en beveiliging. Dienstverleners handelen volgens passende instructies. Contact: hello@movera.ai.")),
  ] }),
  page("terms-and-conditions", t("Terms of use", "شروط الاستخدام", "Conditions d’utilisation", "Gebruiksvoorwaarden"), t("The rules for using MOVERA’s public website and digital services.", "القواعد المنظمة لاستخدام موقع موفيرا العام وخدماته الرقمية.", "Les règles d’utilisation du site public et des services numériques MOVERA.", "De regels voor het gebruik van de publieke MOVERA-website en digitale diensten."), t("Effective 19 August 2026. By using this website, you agree to use it lawfully and respectfully.", "سارية من 19 أغسطس 2026. باستخدام هذا الموقع، توافق على استعماله بصورة قانونية ومسؤولة.", "En vigueur le 19 août 2026. En utilisant ce site, vous acceptez un usage légal et respectueux.", "Geldig vanaf 19 augustus 2026. Door deze website te gebruiken, stemt u in met wettig en respectvol gebruik."), undefined, { displayOrder: 7, sections: [
    section("use", t("Permitted use", "الاستخدام المسموح", "Usage autorisé", "Toegestaan gebruik"), t("You may browse, contact us, subscribe and apply for published roles. Do not disrupt the service, bypass security, submit unlawful material or misrepresent your identity.", "يمكنك التصفح والتواصل والاشتراك والتقدم للوظائف. ويُحظر تعطيل الخدمة أو تجاوز الحماية أو إرسال محتوى غير قانوني أو انتحال الهوية.", "Vous pouvez consulter, nous contacter, vous inscrire et postuler. Il est interdit de perturber le service, contourner la sécurité, soumettre un contenu illicite ou usurper une identité.", "U mag browsen, contact opnemen, inschrijven en solliciteren. U mag de dienst niet verstoren, beveiliging omzeilen, onwettig materiaal indienen of uw identiteit verkeerd voorstellen.")),
    section("content", t("Content and availability", "المحتوى والتوفر", "Contenu et disponibilité", "Inhoud en beschikbaarheid"), t("Content describes MOVERA’s current direction and may change. Reference programmes explain intended approaches and do not create a customer commitment. We aim for availability but do not promise uninterrupted access.", "يصف المحتوى توجه موفيرا الحالي وقد يتغير. وتوضح البرامج المرجعية منهج العمل ولا تنشئ التزاماً تعاقدياً. نسعى إلى الإتاحة من دون ضمان استمرارها بلا انقطاع.", "Le contenu présente l’orientation actuelle de MOVERA et peut évoluer. Les programmes de référence décrivent une approche sans constituer un engagement client. Nous visons la disponibilité sans garantir un accès ininterrompu.", "De inhoud beschrijft de huidige richting van MOVERA en kan wijzigen. Referentieprogramma’s lichten een aanpak toe en vormen geen klantverbintenis. We streven naar beschikbaarheid maar garanderen geen ononderbroken toegang.")),
    section("property", t("Intellectual property", "الملكية الفكرية", "Propriété intellectuelle", "Intellectuele eigendom"), t("MOVERA names, visual identity, website design and original content remain protected. You may link to public pages, but may not republish substantial content or imply endorsement without permission.", "تظل أسماء موفيرا وهويتها البصرية وتصميم الموقع ومحتواه الأصلي محمية. يمكنك مشاركة الروابط، ولا يجوز إعادة نشر محتوى جوهري أو الإيحاء بتأييد من دون إذن.", "Le nom MOVERA, son identité visuelle, le design du site et ses contenus originaux restent protégés. Vous pouvez créer des liens, sans republier une part substantielle ni suggérer un soutien sans autorisation.", "De naam MOVERA, visuele identiteit, het websiteontwerp en originele inhoud blijven beschermd. U mag linken, maar geen wezenlijke inhoud herpubliceren of goedkeuring suggereren zonder toestemming.")),
    section("contact", t("Questions", "الأسئلة", "Questions", "Vragen"), t("Questions can be sent to hello@movera.ai. Belgian and applicable European law govern use of this website, subject to mandatory consumer protections.", "يمكن إرسال الأسئلة إلى hello@movera.ai. يخضع الموقع للقانون البلجيكي والأوروبي المعمول به، مع مراعاة حقوق المستهلك الإلزامية.", "Les questions peuvent être envoyées à hello@movera.ai. Le droit belge et européen applicable régit le site, sous réserve des protections obligatoires.", "Vragen kunt u sturen naar hello@movera.ai. Belgisch en toepasselijk Europees recht beheersen de website, met behoud van dwingende consumentenbescherming.")),
  ] }),
  page("cookie-policy", t("Cookie policy", "سياسة ملفات الارتباط", "Politique relative aux cookies", "Cookiebeleid"), t("Clear choices for necessary storage and optional measurement.", "خيارات واضحة للتخزين الضروري والقياس الاختياري.", "Des choix clairs entre stockage nécessaire et mesure facultative.", "Duidelijke keuzes tussen noodzakelijke opslag en optionele meting."), t("Effective 19 August 2026. The website stores only what is needed to operate unless you actively choose optional categories.", "سارية من 19 أغسطس 2026. لا يخزن الموقع سوى ما يلزم للتشغيل ما لم تختر الفئات الاختيارية صراحة.", "En vigueur le 19 août 2026. Le site ne stocke que le nécessaire, sauf choix actif de catégories facultatives.", "Geldig vanaf 19 augustus 2026. De website bewaart alleen wat nodig is, tenzij u actief optionele categorieën kiest."), undefined, { displayOrder: 8, sections: [
    section("necessary", t("Necessary storage", "التخزين الضروري", "Stockage nécessaire", "Noodzakelijke opslag"), t("Necessary storage supports security, language, accessibility, session and privacy choices. It cannot be switched off because the requested service depends on it.", "يدعم التخزين الضروري الأمن واللغة وسهولة الوصول والجلسة وخيارات الخصوصية. ولا يمكن تعطيله لأن الخدمة المطلوبة تعتمد عليه.", "Le stockage nécessaire soutient sécurité, langue, accessibilité, session et choix de confidentialité. Il ne peut pas être désactivé car le service demandé en dépend.", "Noodzakelijke opslag ondersteunt beveiliging, taal, toegankelijkheid, sessie en privacykeuzes. Ze kan niet worden uitgeschakeld omdat de gevraagde dienst ervan afhangt.")),
    section("optional", t("Optional measurement", "القياس الاختياري", "Mesure facultative", "Optionele meting"), t("If optional analytics are introduced, they remain disabled until you give informed, active consent. Marketing storage is not required to use the website.", "إذا أُضيفت أدوات تحليل اختيارية فستبقى معطلة حتى تمنح موافقة واعية وصريحة. ولا يلزم التخزين التسويقي لاستخدام الموقع.", "Si des outils d’analyse facultatifs sont ajoutés, ils restent désactivés jusqu’à votre consentement actif et informé. Aucun stockage marketing n’est requis.", "Als optionele analytics worden toegevoegd, blijven ze uitgeschakeld tot u actief en geïnformeerd toestemt. Marketingopslag is niet nodig.")),
    section("control", t("Change your choice", "تغيير اختيارك", "Modifier votre choix", "Uw keuze wijzigen"), t("You can reopen cookie preferences from the footer and withdraw optional consent as easily as you gave it. Browser settings can also remove stored data.", "يمكنك إعادة فتح التفضيلات من أسفل الموقع وسحب الموافقة الاختيارية بالسهولة نفسها التي منحتها بها. ويمكن للمتصفح حذف البيانات المخزنة.", "Vous pouvez rouvrir les préférences depuis le pied de page et retirer un consentement facultatif aussi facilement que vous l’avez donné. Le navigateur peut aussi supprimer les données.", "U kunt cookievoorkeuren via de footer opnieuw openen en optionele toestemming even eenvoudig intrekken als geven. Uw browser kan opgeslagen gegevens verwijderen.")),
    section("contact", t("Contact", "التواصل", "Contact", "Contact"), t("Questions about storage or consent can be sent to hello@movera.ai.", "أرسل أسئلتك حول التخزين أو الموافقة إلى hello@movera.ai.", "Toute question sur le stockage ou le consentement peut être envoyée à hello@movera.ai.", "Vragen over opslag of toestemming kunt u sturen naar hello@movera.ai.")),
  ] }),
];

const regions: RegionContent[] = [
  { code: "hub-a", title: t("Brussels & Capital Region", "بروكسل ومنطقة العاصمة", "Bruxelles et Région-Capitale", "Brussel en het Hoofdstedelijk Gewest"), summary: t("Dense multimodal streets where public service, autonomy and accessibility meet.", "شوارع متعددة الوسائط تلتقي فيها الخدمة العامة والقيادة الذاتية وسهولة الوصول.", "Des rues multimodales où se rencontrent service public, autonomie et accessibilité.", "Multimodale straten waar publieke dienstverlening, autonomie en toegankelijkheid samenkomen."), body: t("Brussels is a reference context for mixed traffic, multilingual service and accountable vehicle intelligence.", "تُعد بروكسل سياقاً مرجعياً لحركة المرور المختلطة والخدمة متعددة اللغات وذكاء المركبات المسؤول.", "Bruxelles est un contexte de référence pour le trafic mixte, le service multilingue et l’intelligence véhicule responsable.", "Brussel is een referentiecontext voor gemengd verkeer, meertalige dienstverlening en verantwoorde voertuigintelligentie."), address: t("Belgium · meetings by appointment", "بلجيكا · الاجتماعات بموعد مسبق", "Belgique · rencontres sur rendez-vous", "België · afspraken op aanvraag"), hours: t("Monday–Friday · 09:00–17:00 CET", "الاثنين–الجمعة · 09:00–17:00 بتوقيت وسط أوروبا", "Lundi–vendredi · 09:00–17:00 CET", "Maandag–vrijdag · 09:00–17:00 CET"), email: "hello@movera.ai", cover: img.regionBrussels, capabilities: [t("Mixed-traffic perception", "إدراك حركة المرور المختلطة", "Perception en trafic mixte", "Perceptie in gemengd verkeer"), t("Multilingual service design", "تصميم خدمة متعددة اللغات", "Design de service multilingue", "Meertalig serviceontwerp"), t("Public mobility operations", "عمليات التنقل العام", "Opérations de mobilité publique", "Publieke mobiliteitsoperaties")] },
  { code: "hub-b", title: t("Flanders Mobility Corridor", "ممر التنقل في فلاندرز", "Corridor mobilité en Flandre", "Vlaamse mobiliteitscorridor"), summary: t("A connected landscape for ports, logistics, cycling and electric fleets.", "مشهد متصل للموانئ والخدمات اللوجستية والدراجات والأساطيل الكهربائية.", "Un territoire connecté pour ports, logistique, vélo et flottes électriques.", "Een verbonden landschap voor havens, logistiek, fietsen en elektrische vloten."), body: t("Flanders is a reference for high-intensity fleet coordination, charging operations and urban-industrial networks.", "توفر فلاندرز سياقاً مرجعياً لتنسيق الأساطيل وعمليات الشحن والشبكات الحضرية والصناعية.", "La Flandre offre un contexte de référence pour la coordination des flottes, la recharge et les réseaux urbains et industriels.", "Vlaanderen biedt een referentie voor vlootcoördinatie, laadoperaties en stedelijke en industriële netwerken."), address: t("Belgium · meetings by appointment", "بلجيكا · الاجتماعات بموعد مسبق", "Belgique · rencontres sur rendez-vous", "België · afspraken op aanvraag"), hours: t("Monday–Friday · 09:00–17:00 CET", "الاثنين–الجمعة · 09:00–17:00 بتوقيت وسط أوروبا", "Lundi–vendredi · 09:00–17:00 CET", "Maandag–vrijdag · 09:00–17:00 CET"), email: "hello@movera.ai", cover: img.regionFlanders, capabilities: [t("Fleet intelligence", "ذكاء الأساطيل", "Intelligence de flotte", "Vlootintelligentie"), t("Charging coordination", "تنسيق الشحن", "Coordination de la recharge", "Laadcoördinatie"), t("Port and logistics mobility", "تنقل الموانئ والخدمات اللوجستية", "Mobilité portuaire et logistique", "Haven- en logistieke mobiliteit")] },
  { code: "hub-c", title: t("Wallonia Mobility Corridor", "ممر التنقل في والونيا", "Corridor mobilité en Wallonie", "Waalse mobiliteitscorridor"), summary: t("Connected movement across towns, research campuses and regional transport.", "حركة متصلة بين المدن ومراكز البحث والنقل الإقليمي.", "Des déplacements connectés entre villes, campus de recherche et transport régional.", "Verbonden beweging tussen steden, onderzoekscampussen en regionaal vervoer."), body: t("Wallonia is a reference for linking shuttles, rail, active mobility and lower-density communities without compromising accessibility.", "توفر والونيا سياقاً لربط المركبات والقطارات والتنقل النشط والمجتمعات الأقل كثافة مع الحفاظ على سهولة الوصول.", "La Wallonie offre un contexte pour relier navettes, rail, mobilité active et territoires moins denses sans sacrifier l’accessibilité.", "Wallonië biedt een referentie om shuttles, spoor, actieve mobiliteit en minder dichte gemeenschappen te verbinden zonder toegankelijkheid op te geven."), address: t("Belgium · meetings by appointment", "بلجيكا · الاجتماعات بموعد مسبق", "Belgique · rencontres sur rendez-vous", "België · afspraken op aanvraag"), hours: t("Monday–Friday · 09:00–17:00 CET", "الاثنين–الجمعة · 09:00–17:00 بتوقيت وسط أوروبا", "Lundi–vendredi · 09:00–17:00 CET", "Maandag–vrijdag · 09:00–17:00 CET"), email: "hello@movera.ai", cover: img.regionWallonia, capabilities: [t("Regional corridor design", "تصميم الممرات الإقليمية", "Conception de corridors régionaux", "Regionaal corridorontwerp"), t("Mobility simulation", "محاكاة التنقل", "Simulation mobilité", "Mobiliteitssimulatie"), t("Accessible first and last mile", "مرحلة أولى وأخيرة مهيأة", "Premier et dernier kilomètre accessibles", "Toegankelijke eerste en laatste kilometer")] },
];

const brandMark = media("movera-mark", "/branding/movera-mark.svg", t("MOVERA mark", "رمز موفيرا", "Symbole MOVERA", "MOVERA-beeldmerk"));
const brandWordmark = media("movera-wordmark", "/branding/movera-wordmark.svg", t("MOVERA wordmark", "اسم موفيرا", "Nom MOVERA", "MOVERA-woordmerk"));
const brandLockup = media("movera-lockup", "/branding/movera-lockup.svg", same("MOVERA"));

const ceoMessage: NonNullable<SiteData["ceoMessage"]> = {
  slug: "ceo-message",
  title: t("Capability and responsibility must move together", "القدرة والمسؤولية تتحركان معاً", "Capacité et responsabilité doivent avancer ensemble", "Vermogen en verantwoordelijkheid moeten samen bewegen"),
  name: t("MOVERA leadership team", "فريق قيادة موفيرا", "Équipe de direction MOVERA", "MOVERA-leiderschapsteam"),
  position: t("Mobility intelligence in Belgium", "ذكاء التنقل في بلجيكا", "Intelligence mobilité en Belgique", "Mobiliteitsintelligentie in België"),
  message: [
    t("Autonomous and connected mobility will change how people experience streets, services and distance. Its value will be measured by how reliably it helps people move.", "سيغير التنقل الذاتي والمتصل تجربة الناس للشارع والخدمة والمسافة. وستُقاس قيمته بقدرته الموثوقة على مساعدة الناس في الحركة.", "La mobilité autonome et connectée transformera notre rapport à la rue, au service et à la distance. Sa valeur se mesurera à sa fiabilité pour faire avancer les personnes.", "Autonome en verbonden mobiliteit verandert hoe mensen straten, diensten en afstand ervaren. De waarde wordt gemeten aan hoe betrouwbaar ze mensen helpt bewegen."),
    t("MOVERA keeps human understanding close to system capability. Every signal needs context, every automated action needs limits and every difficult decision needs an accountable owner.", "تُبقي موفيرا فهم الإنسان قريباً من قدرة النظام. فكل إشارة تحتاج إلى سياق، وكل إجراء مؤتمت إلى حدود، وكل قرار صعب إلى مسؤول واضح.", "MOVERA maintient la compréhension humaine au plus près du système. Chaque signal a besoin de contexte, chaque action automatisée de limites et chaque décision difficile d’un responsable.", "MOVERA houdt menselijk begrip dicht bij systeemvermogen. Elk signaal vraagt context, elke geautomatiseerde actie grenzen en elke moeilijke beslissing een verantwoordelijke eigenaar."),
    t("Belgium gives us the right place to build this approach: multilingual, multimodal and demanding collaboration across public and private systems.", "وتمنحنا بلجيكا البيئة المناسبة لهذا النهج: تعدد لغوي ووسائط نقل متنوعة وتعاون دقيق بين الأنظمة العامة والخاصة.", "La Belgique offre le bon terrain : multilingue, multimodale et exigeante dans la collaboration entre systèmes publics et privés.", "België biedt daarvoor de juiste omgeving: meertalig, multimodaal en veeleisend in samenwerking tussen publieke en private systemen."),
  ],
  pullQuote: t("Make movement more capable by making every important decision clearer.", "نجعل الحركة أكثر قدرة عندما نجعل كل قرار مهم أكثر وضوحاً.", "Rendre le mouvement plus capable en clarifiant chaque décision importante.", "Maak beweging krachtiger door elke belangrijke beslissing duidelijker te maken."),
  portrait: img.aboutStudio,
  seo: { title: t("Leadership note | MOVERA", "رسالة القيادة | موفيرا", "Message de la direction | MOVERA", "Boodschap van het leiderschap | MOVERA"), description: t("MOVERA’s view on accountable mobility intelligence in Belgium.", "رؤية موفيرا لذكاء التنقل المسؤول في بلجيكا.", "La vision MOVERA d’une intelligence mobilité responsable en Belgique.", "MOVERA’s visie op verantwoorde mobiliteitsintelligentie in België."), keywords: t("MOVERA, Belgium, mobility leadership", "موفيرا، بلجيكا، قيادة التنقل", "MOVERA, Belgique, direction mobilité", "MOVERA, België, mobiliteitsleiderschap") },
  status: "published",
};

export const starterSiteData: SiteData = {
  homepage: {
    hero: {
      eyebrow: t("MOBILITY INTELLIGENCE", "ذكاء التنقل", "INTELLIGENCE MOBILITÉ", "MOBILITEITSINTELLIGENTIE"),
      title: t("Move intelligence into motion.", "نحوّل الذكاء إلى حركة.", "Mettre l’intelligence en mouvement.", "Breng intelligentie in beweging."),
      description: t("MOVERA connects autonomous vehicles, mobility operations and human decisions for Belgium’s moving world.", "تربط موفيرا المركبات الذاتية بعمليات التنقل والقرار البشري لخدمة عالم بلجيكي دائم الحركة.", "MOVERA relie véhicules autonomes, opérations de mobilité et décisions humaines pour une Belgique en mouvement.", "MOVERA verbindt autonome voertuigen, mobiliteitsoperaties en menselijke beslissingen voor een België in beweging."),
      primaryLabel: t("Explore the mobility stack", "استكشف منظومة التنقل", "Explorer la plateforme mobilité", "Ontdek het mobiliteitsplatform"), primaryHref: "/products",
      secondaryLabel: t("Talk to MOVERA", "تحدث مع موفيرا", "Parler à MOVERA", "Praat met MOVERA"), secondaryHref: "/contact", background: hero,
    },
    intro: { title: t("Mobility becomes intelligent when decisions become clear.", "يصبح التنقل ذكياً عندما تصبح القرارات واضحة.", "La mobilité devient intelligente lorsque les décisions deviennent claires.", "Mobiliteit wordt intelligent wanneer beslissingen duidelijk worden."), body: t("MOVERA turns vehicle signals, service context and human authority into one accountable path from perception to action.", "تحوّل موفيرا إشارات المركبة وسياق الخدمة والقرار البشري إلى مسار واحد خاضع للمساءلة من الإدراك إلى الإجراء.", "MOVERA transforme signaux véhicule, contexte de service et autorité humaine en un chemin responsable de la perception à l’action.", "MOVERA maakt van voertuigsignalen, servicecontext en menselijke bevoegdheid één verantwoord pad van perceptie naar actie.") },
    stats: [
      { value: "01", label: t("Perceive", "نرصد", "Percevoir", "Waarnemen") },
      { value: "02", label: t("Understand", "نفهم", "Comprendre", "Begrijpen") },
      { value: "03", label: t("Coordinate", "ننسّق", "Coordonner", "Coördineren") },
      { value: "04", label: t("Learn", "نتعلم", "Apprendre", "Leren") },
    ],
    featuredServices: services.map(value => value.id), featuredProjects: projects.map(value => value.id), latestNews: news.map(value => value.id),
    bands: [
      { id: "locations", visible: true, itemIds: [], eyebrow: t("Belgian context", "السياق البلجيكي", "Contexte belge", "Belgische context"), title: t("Built for movement across regions.", "مصممة لحركة تربط المناطق.", "Pensée pour relier les régions.", "Gebouwd voor beweging over regio’s heen."), body: t("Brussels, Flanders and Wallonia each reveal a different mobility challenge.", "تكشف بروكسل وفلاندرز ووالونيا عن تحديات مختلفة للتنقل.", "Bruxelles, la Flandre et la Wallonie révèlent chacune un défi différent.", "Brussel, Vlaanderen en Wallonië tonen elk een andere mobiliteitsuitdaging."), viewLabel: t("Explore the regions", "استكشف المناطق", "Explorer les régions", "Ontdek de regio’s") },
      { id: "news", visible: true, itemIds: news.map(value => value.id), eyebrow: t("Signal feed", "موجز الإشارات", "Fil des signaux", "Signaalfeed"), title: t("The thinking behind movement.", "الأفكار التي تقود الحركة.", "La réflexion derrière le mouvement.", "Het denken achter beweging."), body: t("Company news and practical mobility perspectives from Belgium.", "أخبار الشركة ورؤى عملية حول التنقل من بلجيكا.", "Actualités et perspectives pratiques sur la mobilité depuis la Belgique.", "Bedrijfsnieuws en praktische mobiliteitsperspectieven uit België."), viewLabel: t("Open the signal feed", "افتح موجز الإشارات", "Ouvrir le fil", "Open de signaalfeed") },
      { id: "products", visible: true, itemIds: products.map(value => value.id), eyebrow: t("The MOVERA stack", "منظومة موفيرا", "La plateforme MOVERA", "Het MOVERA-platform"), title: t("From perception to action.", "من الإدراك إلى الإجراء.", "De la perception à l’action.", "Van perceptie naar actie."), body: t("Four product foundations for vehicles, fleets and mobility networks.", "أربعة أسس للمركبات والأساطيل وشبكات التنقل.", "Quatre fondations pour véhicules, flottes et réseaux de mobilité.", "Vier fundamenten voor voertuigen, vloten en mobiliteitsnetwerken."), viewLabel: t("View products", "عرض المنتجات", "Voir les produits", "Bekijk producten") },
      { id: "projects", visible: true, itemIds: projects.map(value => value.id), eyebrow: t("Reference programmes", "البرامج المرجعية", "Programmes de référence", "Referentieprogramma’s"), title: t("Make progress visible.", "نجعل التقدم واضحاً.", "Rendre le progrès visible.", "Maak vooruitgang zichtbaar."), body: t("Belgian contexts for perception, fleets, cockpits and connected corridors.", "سياقات بلجيكية للإدراك والأساطيل وقمرات القيادة والممرات المتصلة.", "Des contextes belges pour perception, flottes, cockpits et corridors connectés.", "Belgische contexten voor perceptie, vloten, cockpits en verbonden corridors."), viewLabel: t("View programmes", "عرض البرامج", "Voir les programmes", "Bekijk programma’s") },
      { id: "careers", visible: false, itemIds: jobs.map(value => value.id), eyebrow: t("Careers", "الوظائف", "Carrières", "Jobs"), title: t("Build the next move.", "ابنِ الخطوة التالية.", "Construire le prochain mouvement.", "Bouw de volgende beweging."), body: t("Work where mobility engineering meets service responsibility.", "اعمل حيث تلتقي هندسة التنقل بمسؤولية الخدمة.", "Travailler là où l’ingénierie rencontre la responsabilité de service.", "Werk waar mobiliteitsengineering en serviceverantwoordelijkheid samenkomen."), viewLabel: t("View roles", "عرض الوظائف", "Voir les postes", "Bekijk vacatures") },
      { id: "customers", visible: false, itemIds: [], eyebrow: t("Partnerships", "الشراكات", "Partenariats", "Partnerschappen"), title: t("Movement is built together.", "الحركة تُبنى معاً.", "Le mouvement se construit ensemble.", "Beweging bouw je samen."), body: t("Shared evidence and clear roles across the mobility ecosystem.", "أدلة مشتركة وأدوار واضحة عبر منظومة التنقل.", "Preuves partagées et rôles clairs dans l’écosystème mobilité.", "Gedeeld bewijs en duidelijke rollen in het mobiliteitsecosysteem."), viewLabel: t("Our approach", "منهجنا", "Notre approche", "Onze aanpak") },
    ],
    cta: { title: t("Stay close to the signal.", "ابق قريباً من الإشارة.", "Restez au plus près du signal.", "Blijf dicht bij het signaal."), body: t("Company updates and practical thinking from the systems behind movement.", "أخبار الشركة وأفكار عملية من الأنظمة التي تقف خلف الحركة.", "Actualités et réflexions pratiques sur les systèmes derrière le mouvement.", "Bedrijfsupdates en praktische inzichten uit de systemen achter beweging."), label: t("Open channel", "افتح القناة", "Ouvrir le canal", "Open het kanaal"), href: "/news" },
  },
  ceoMessage,
  assistant: { label: t("Ask MOVERA", "اسأل موفيرا", "Demander à MOVERA", "Vraag MOVERA"), icon: media("assistant", "movera-chatbot.webp", t("Open the MOVERA assistant", "افتح مساعد موفيرا", "Ouvrir l’assistant MOVERA", "Open de MOVERA-assistent")) },
  brand: { logo: brandLockup, logoLight: brandLockup, logoDark: brandLockup, mark: brandMark, markLight: brandMark, markDark: brandMark, wordmark: brandWordmark, wordmarkLight: brandWordmark, wordmarkDark: brandWordmark, wordmarkText: same("MOVERA"), aiLabel: t("Mobility intelligence", "ذكاء التنقل", "Intelligence mobilité", "Mobiliteitsintelligentie"), aiEnabled: true },
  appearance: { defaultTheme: "light" },
  news, blogs, projects, services, products, pages: [...aboutPages, ...legalPages], jobs, innovation, regions,
  footer: { contactLabel: t("Talk to MOVERA", "تحدث مع موفيرا", "Parler à MOVERA", "Praat met MOVERA"), locationLabel: t("Belgium", "بلجيكا", "Belgique", "België"), workingHoursLabel: t("Availability", "التوفر", "Disponibilité", "Beschikbaarheid"), phone: "", email: "hello@movera.ai", address: t("Belgium · meetings by appointment", "بلجيكا · الاجتماعات بموعد مسبق", "Belgique · rencontres sur rendez-vous", "België · afspraken op aanvraag"), hours: t("Monday–Friday · 09:00–17:00 CET", "الاثنين–الجمعة · 09:00–17:00 بتوقيت وسط أوروبا", "Lundi–vendredi · 09:00–17:00 CET", "Maandag–vrijdag · 09:00–17:00 CET"), socialLinks: { facebook: "", instagram: "", youtube: "", linkedin: "" } },
  deletedContentIds: {}, trash: [],
};
